SELECT
    case_number,
    case_id,
    account_id,
    agent_name,
    agent_email,
    agent_company,
    case_source,
    case_status,
    case_type,
    case_subtype,
    channel_name,
    origin,
    product_flag,
    product_preference,
    current_value_band,
    current_casino_segment,
    current_state,
    registration_state,
    lifecycle,
    is_closed,
    is_escalated,
    is_contained,
    is_any_vip,
    is_ai_agent,
    csat_score,
    case_time_minutes,
    case_closed_count,
    kyc_decision,
    case_created_est,
    case_closed_est,
    last_modified_est,
    chat_full_transcript,
    chat_agent_transcript,
    chat_customer_transcript,
    chat_bot_transcript,
    customer_comments
FROM FBG_ANALYTICS.OPERATIONS.CS_CASES
WHERE chat_full_transcript IS NOT NULL
ORDER BY case_created_est DESC
LIMIT 50;
